# Generated by Django 5.1.6 on 2025-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('fecha_hora', models.DateTimeField()),
                ('paciente', models.CharField(editable=False, max_length=255)),
                ('tipo_cita', models.CharField(choices=[('Consulta', 'Consulta'), ('Servicio', 'Servicio'), ('Tratamiento', 'Tratamiento')], max_length=100)),
                ('medico', models.CharField(max_length=255)),
                ('numero_cita', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
    ]
